### PR TITLE
[bionic] use ruby3 image for testing

### PR DESCRIPTION
**Pull request by ramonskie**

### CODE REVIEW

**Comment by ramonskie** [comment]
im not sure how this will affect xenial builds.

**Comment by bgandon** [comment]
Where is the `Dockerfile` for that `bosh/main-ruby-go` image, by the way?

**Comment by ramonskie** [comment]
> Where is the `Dockerfile` for that `bosh/main-ruby-go` image, by the way?

https://github.com/cloudfoundry/bosh/tree/master/ci/dockerfiles/main-ruby-go

**Comment by rkoster** [comment]
LGTM

**Pull request merged**
